version: '2'
services:
    webpaymentextract-app:
        image: webpaymentextract
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://webpaymentextract-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8082:8082
    webpaymentextract-mssql:
        extends:
            file: mssql.yml
            service: webpaymentextract-mssql
